"""Type stubs for the Rust native extension module."""

from typing import List, Optional

__version__: str

class TorConfig:
    data_dir: Optional[str]
    bridges: List[str]
    isolation: bool

    def __init__(
        self,
        data_dir: Optional[str] = None,
        bridges: List[str] = ...,
        isolation: bool = False,
    ) -> None: ...

class TorTunnel:
    _isolation: bool
    def __init__(self, config: TorConfig) -> None: ...
    def create_stream(self, host: str, port: int) -> TorStream: ...
    def create_isolated_stream(self, host: str, port: int) -> TorStream: ...
    def close(self) -> None: ...
    def is_alive(self) -> bool: ...

class TorStream:
    def send(self, data: bytes) -> int: ...
    def recv(self, max_bytes: int, timeout_ms: Optional[int] = None) -> bytes: ...
    def close(self) -> None: ...
    def is_connected(self) -> bool: ...
